version: '3'
services:


  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=notification_connection
      - POSTGRES_PASSWORD=notification_connection
      - POSTGRES_DB=notification_service
#      - POSTGRES_MULTIPLE_DATABASES=notification_service
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../postgres-init-scripts:/docker-entrypoint-initdb.d


  minio:
    container_name: minio
    restart: "no"
    image: minio/minio:RELEASE.2024-03-26T22-10-45Z
    ports:
      - "8999:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    entrypoint: sh
    command: -c 'mkdir -p /data/local-files && /usr/bin/minio server --console-address ":9001" /data'


  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.8.0
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"


  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.8.0
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: "notificationTopic, deadLetterTopic"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  fake-smtp:
    container_name: fake-smtp
    build:
      context: ../fake-smtp/application
      dockerfile: fake-smtp-Dockerfile
    volumes:
      - emails:/emails:cached
    ports:
      - "2525:2525"

volumes:
  pg_data:
  minio-storage:
  emails: