server:
  port: 8081

storage:
  sourcelocation: storage/upload-dir
  resultlocation: storage/result-dir
  changeslocation: storage/changes-dir

spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  application:
    name: DocxVersionControl

