server:
  port: 8081

storage:
  sourcelocation: storage/upload-dir
  resultlocation: storage/result-dir
  changeslocation: storage/changes-dir

spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  application:
    name: DocxVersionControl

minio:
  url: http://127.0.0.1:9000
  access:
    username: minioadmin
    password: minioadmin
  bucket:
    name: documentbucket